image:
 - Ubuntu
 - Visual Studio 2017

environment:
  CURL_VERSION: 7.56.1
  CEF_VERSION: 75.1.16+g16a67c4+chromium-75.0.3770.100
  APPVEYOR_YML_DISABLE_PS_LINUX: true
  TWITCH-CLIENTID:
    secure: 8clMbOxjSzj/5psxvegb31MxWKUcWQ7S/LaAzFGqGoM=
  TWITCH-HASH:
    secure: BOdltYA5wo57aM1lBe9tiEfJz27uiMEnWEs3/Mi9mLU=

install:
  - git submodule update --init --recursive
  - cmd: C:\projects\obs-studio\CI\install-qt-win.cmd
  - cmd: C:\projects\obs-studio\CI\install-script-win.cmd
  - sh: ./CI/install-dependencies-linux-ubuntu16.sh
  - sh: ./CI/before-script-linux.sh
  - sh: ./CI/install-script-linux.sh

build_script:
  - cmd: call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build32\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cmd: call msbuild /m /p:Configuration=%build_config% C:\projects\obs-studio\build64\obs-studio.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - sh: cd ./build && make -j4 && cd -

before_deploy:
  - cmd: C:\projects\obs-studio\CI\before-deploy-win.cmd

deploy_script:
  - ps: Push-AppveyorArtifact "build.zip" -FileName "$(git describe).zip"

test: off

cache:
  - dependencies2017.zip
  - vlc.zip
  - 'cef_binary_%CEF_VERSION%_windows32_minimal.zip'
  - 'cef_binary_%CEF_VERSION%_windows64_minimal.zip'
  - Qt_5.10.1.7z
